#!/usr/bin/env bash

##? Start a stoped container
##?
##? Usage:
##?    start

if docker ps > /dev/null 2>&1; then

  container=$(docker container ls | awk '{if(NR!=1) print $1 ": " $(NF)}' | fzf --height 40%)

  if [[ -n $container ]]; then
    container_id=$(echo $container | awk -F ': ' '{print $1}')
    docker stop $container_id
  else
    echo "You haven't selected any container!"
  fi
else
  echo "Docker daemon is not running!"
fi
