#!/usr/bin/env bash

source "$DOTLY_PATH/scripts/core/_main.sh"

##? This command will revert permissions for all modified files
##?
##? Usage:
##?    reset-permissions

if (! git::is_in_repo); then
  echo "The current path doesn't have a git repo 😞"
  exit 0
fi

git diff -p -R --no-ext-diff --no-color | grep -E "^(diff|(old|new) mode)" --color=never | git apply
echo "Permissions reverted"
